name: Docker Test & Publish

on:
  push:
    tags:
      - "*"
  pull_request:
    paths:
      - "Dockerfile"
      - "**/Dockerfile"
      - ".github/workflows/docker.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  base:
    name: Test base image build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          cache-from: type=gha,scope=buildx-base-multi-arch
          cache-to: type=gha,scope=buildx-base-multi-arch,mode=max

  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    name: Publish Docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push base image
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          cache-from: type=gha,scope=buildx-base-multi-arch
          cache-to: type=gha,scope=buildx-base-multi-arch,mode=max

      # stoatchat/api (delta)
      - name: Docker meta - API
        id: meta-delta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-api
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/delta/Dockerfile
          tags: ${{ steps.meta-delta.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-delta.outputs.labels }}
          cache-from: type=gha,scope=buildx-delta
          cache-to: type=gha,scope=buildx-delta,mode=max

      # stoatchat/events (bonfire)
      - name: Docker meta - Events
        id: meta-bonfire
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-events
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Events
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/bonfire/Dockerfile
          tags: ${{ steps.meta-bonfire.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-bonfire.outputs.labels }}
          cache-from: type=gha,scope=buildx-bonfire
          cache-to: type=gha,scope=buildx-bonfire,mode=max

      # stoatchat/file-server (autumn)
      - name: Docker meta - File Server
        id: meta-autumn
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-file-server
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push File Server
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/autumn/Dockerfile
          tags: ${{ steps.meta-autumn.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-autumn.outputs.labels }}
          cache-from: type=gha,scope=buildx-autumn
          cache-to: type=gha,scope=buildx-autumn,mode=max

      # stoatchat/proxy (january)
      - name: Docker meta - Proxy
        id: meta-january
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-proxy
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Proxy
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/january/Dockerfile
          tags: ${{ steps.meta-january.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-january.outputs.labels }}
          cache-from: type=gha,scope=buildx-january
          cache-to: type=gha,scope=buildx-january,mode=max

      # stoatchat/gifbox
      - name: Docker meta - Gifbox
        id: meta-gifbox
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-gifbox
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Gifbox
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/services/gifbox/Dockerfile
          tags: ${{ steps.meta-gifbox.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-gifbox.outputs.labels }}
          cache-from: type=gha,scope=buildx-gifbox
          cache-to: type=gha,scope=buildx-gifbox,mode=max

      # stoatchat/crond
      - name: Docker meta - Crond
        id: meta-crond
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-crond
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Crond
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/crond/Dockerfile
          tags: ${{ steps.meta-crond.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-crond.outputs.labels }}
          cache-from: type=gha,scope=buildx-crond
          cache-to: type=gha,scope=buildx-crond,mode=max

      # stoatchat/pushd
      - name: Docker meta - Pushd
        id: meta-pushd
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-pushd
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Pushd
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/pushd/Dockerfile
          tags: ${{ steps.meta-pushd.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-pushd.outputs.labels }}
          cache-from: type=gha,scope=buildx-pushd
          cache-to: type=gha,scope=buildx-pushd,mode=max

      # stoatchat/voice-ingress
      - name: Docker meta - Voice Ingress
        id: meta-voice-ingress
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stoatchat-voice-ingress
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Voice Ingress
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: crates/daemons/voice-ingress/Dockerfile
          tags: ${{ steps.meta-voice-ingress.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/stoatchat-base:latest
          labels: ${{ steps.meta-voice-ingress.outputs.labels }}
          cache-from: type=gha,scope=buildx-voice-ingress
          cache-to: type=gha,scope=buildx-voice-ingress,mode=max
